version: "2"
services:
  ldd-transform:
    container_name: ldd-transform
    restart: always
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./services.env