version: "2"
services:
  ldd-transform:
    container_name: ldd-transform
    restart: always
    build: .
    ports:
      - "49160:3001"
    environment:
      - NODE_ENV=production
  lddtool-web-service:
    container_name: lddtool-web-service
    restart: always
    build: lddtool-web-service
    ports:
      - "3002:3002"
    environment:
      - BASE=/